<?php

return [
    'admin_debit'           => 'Biaya Admin QRIS',
    'admin_kredit'          => 'Biaya Admin EDC',
    'akun_id'               => 'Jenis Penerimaan',
    'bank_tujuan'           => 'Bank',
    'cara_pembayaran'       => 'Cara Pembayaran',
    'carabayar_id'          => 'Cara Bayar',
    'instalasi_id'          => 'Instalasi',
    'jenis_tagihan'         => 'Jenis Tagihan',
    'jumlah_netto'          => 'Jumlah Netto',
    'kartubank_pasien'      => 'Nama Bank',
    'kasir_id'              => 'Kasir',
    'klasifikasi'           => 'Klasifikasi',
    'loket_id'              => 'Loket',
    'no_buktibayar'         => 'No Kwitansi',
    'no_closingkasir'       => 'No. Closing Kasir',
    'no_dokumen'            => 'No. Dokumen',
    'no_kartubank_pasien'   => 'No. Kartu Bank',
    'no_pendaftaran'        => 'No. Pendaftaran',
    'no_rekam_medik'        => 'No. Rekam Medik',
    'pasien_alamat'         => 'Alamat Pasien',
    'pasien_nama'           => 'Nama Pasien',
    'penjamin_id'           => 'Penjamin',
    'pihak3'                => 'Penyetor',
    'rek_id'                => 'Rekening DPA',
    'selisih'               => 'Selisih',
    'status_id'             => 'Status',
    'tgl_buktibayar'        => 'Tanggal Kwitansi',
    'tgl_closingkasir'      => 'Tgl. Closing Kasir',
    'tgl_krs'               => 'Tgl. KRS',
    'tgl_pendaftaran'       => 'Tgl. Pendaftaran',
    'tgl_pelayanan'         => 'Tgl. Pelayanan',
    'total'                 => 'Jumlah Bayar',
];
